<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerORphDUv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerORphDUv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerORphDUv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerORphDUv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerORphDUv\App_KernelDevDebugContainer([
    'container.build_hash' => 'ORphDUv',
    'container.build_id' => '203217cf',
    'container.build_time' => 1619605231,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerORphDUv');
